FROM node:24.14
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
# openapi-generator-cli の実行にJavaが必要
RUN apt-get update && apt-get install -y --no-install-recommends default-jre-headless && rm -rf /var/lib/apt/lists/*
WORKDIR /app/frontend
COPY ./frontend/package.json ./frontend/pnpm-lock.yaml /app/frontend/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY ./docs/openapi/ /app/docs/openapi/
RUN pnpm generate
CMD ["pnpm", "dev", "--host"]
