services:
  app:
    profiles: [prod]
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      TZ: Asia/Tokyo
    env_file:
      - backend/.env
      - database/.env
    depends_on:
      db:
        condition: service_healthy

  migrate:
    profiles: [migrate]
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    environment:
      TZ: Asia/Tokyo
    env_file:
      - database/.env
    depends_on:
      db:
        condition: service_healthy

  backend:
    profiles: [dev]
    build:
      context: .
      dockerfile: docker/app/Dockerfile.backend.dev
    volumes:
      - ./backend:/app/backend
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      TZ: Asia/Tokyo
    env_file:
      - backend/.env
      - database/.env
    depends_on:
      db:
        condition: service_healthy
  frontend:
    profiles: [dev]
    build:
      context: .
      dockerfile: docker/app/Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - backend

  db:
    image: mysql:8.4
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
    env_file:
      - database/.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "root", "-p$$MYSQL_PASSWORD"]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 30s

volumes:
  dbdata: null
