// Code generated by MockGen. DO NOT EDIT.
// Source: work.go
//
// Generated by this command:
//
//	mockgen -source=work.go -destination=mock/mock_work.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	schema "tsumiki/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkRepository is a mock of WorkRepository interface.
type MockWorkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkRepositoryMockRecorder is the mock recorder for MockWorkRepository.
type MockWorkRepositoryMockRecorder struct {
	mock *MockWorkRepository
}

// NewMockWorkRepository creates a new mock instance.
func NewMockWorkRepository(ctrl *gomock.Controller) *MockWorkRepository {
	mock := &MockWorkRepository{ctrl: ctrl}
	mock.recorder = &MockWorkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkRepository) EXPECT() *MockWorkRepositoryMockRecorder {
	return m.recorder
}

// CreateWork mocks base method.
func (m *MockWorkRepository) CreateWork(userID int, title string, visibility string, description string, thumbnailID *int) (*schema.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWork", userID, title, visibility, description, thumbnailID)
	ret0, _ := ret[0].(*schema.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWork indicates an expected call of CreateWork.
func (mr *MockWorkRepositoryMockRecorder) CreateWork(userID, title, visibility, description, thumbnailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWork", reflect.TypeOf((*MockWorkRepository)(nil).CreateWork), userID, title, visibility, description, thumbnailID)
}

// DeleteWork mocks base method.
func (m *MockWorkRepository) DeleteWork(workID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWork", workID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWork indicates an expected call of DeleteWork.
func (mr *MockWorkRepositoryMockRecorder) DeleteWork(workID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWork", reflect.TypeOf((*MockWorkRepository)(nil).DeleteWork), workID)
}

// GetWork mocks base method.
func (m *MockWorkRepository) GetWork(workID int) (*schema.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWork", workID)
	ret0, _ := ret[0].(*schema.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWork indicates an expected call of GetWork.
func (mr *MockWorkRepositoryMockRecorder) GetWork(workID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWork", reflect.TypeOf((*MockWorkRepository)(nil).GetWork), workID)
}

// GetWorks mocks base method.
func (m *MockWorkRepository) GetWorks(watchUserID *int, pageSize, page int) ([]schema.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorks", watchUserID, pageSize, page)
	ret0, _ := ret[0].([]schema.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorks indicates an expected call of GetWorks.
func (mr *MockWorkRepositoryMockRecorder) GetWorks(watchUserID, pageSize, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorks", reflect.TypeOf((*MockWorkRepository)(nil).GetWorks), watchUserID, pageSize, page)
}

// UpdateWork mocks base method.
func (m *MockWorkRepository) UpdateWork(workID int, title string, visibility string, description string) (*schema.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWork", workID, title, visibility, description)
	ret0, _ := ret[0].(*schema.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWork indicates an expected call of UpdateWork.
func (mr *MockWorkRepositoryMockRecorder) UpdateWork(workID, title, visibility, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWork", reflect.TypeOf((*MockWorkRepository)(nil).UpdateWork), workID, title, visibility, description)
}

// UpdateWorkThumbnail mocks base method.
func (m *MockWorkRepository) UpdateWorkThumbnail(workID int, thumbnailID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkThumbnail", workID, thumbnailID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkThumbnail indicates an expected call of UpdateWorkThumbnail.
func (mr *MockWorkRepositoryMockRecorder) UpdateWorkThumbnail(workID, thumbnailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkThumbnail", reflect.TypeOf((*MockWorkRepository)(nil).UpdateWorkThumbnail), workID, thumbnailID)
}
