// Code generated by MockGen. DO NOT EDIT.
// Source: tsumiki.go
//
// Generated by this command:
//
//	mockgen -source=tsumiki.go -destination=mock/mock_tsumiki.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	schema "tsumiki/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockTsumikiRepository is a mock of TsumikiRepository interface.
type MockTsumikiRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTsumikiRepositoryMockRecorder
	isgomock struct{}
}

// MockTsumikiRepositoryMockRecorder is the mock recorder for MockTsumikiRepository.
type MockTsumikiRepositoryMockRecorder struct {
	mock *MockTsumikiRepository
}

// NewMockTsumikiRepository creates a new mock instance.
func NewMockTsumikiRepository(ctrl *gomock.Controller) *MockTsumikiRepository {
	mock := &MockTsumikiRepository{ctrl: ctrl}
	mock.recorder = &MockTsumikiRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTsumikiRepository) EXPECT() *MockTsumikiRepositoryMockRecorder {
	return m.recorder
}

// CreateMedia mocks base method.
func (m *MockTsumikiRepository) CreateMedia(tsumikiID int, mediaType string, url string) (*schema.TsumikiBlockMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedia", tsumikiID, mediaType, url)
	ret0, _ := ret[0].(*schema.TsumikiBlockMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMedia indicates an expected call of CreateMedia.
func (mr *MockTsumikiRepositoryMockRecorder) CreateMedia(tsumikiID, mediaType, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedia", reflect.TypeOf((*MockTsumikiRepository)(nil).CreateMedia), tsumikiID, mediaType, url)
}

// CreateTsumiki mocks base method.
func (m *MockTsumikiRepository) CreateTsumiki(userID int, title string, visibility string, workID *int, thumbnailID int) (*schema.Tsumiki, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTsumiki", userID, title, visibility, workID, thumbnailID)
	ret0, _ := ret[0].(*schema.Tsumiki)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTsumiki indicates an expected call of CreateTsumiki.
func (mr *MockTsumikiRepositoryMockRecorder) CreateTsumiki(userID, title, visibility, workID, thumbnailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTsumiki", reflect.TypeOf((*MockTsumikiRepository)(nil).CreateTsumiki), userID, title, visibility, workID, thumbnailID)
}

// DeleteTsumiki mocks base method.
func (m *MockTsumikiRepository) DeleteTsumiki(tsumikiID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTsumiki", tsumikiID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTsumiki indicates an expected call of DeleteTsumiki.
func (mr *MockTsumikiRepositoryMockRecorder) DeleteTsumiki(tsumikiID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTsumiki", reflect.TypeOf((*MockTsumikiRepository)(nil).DeleteTsumiki), tsumikiID)
}

// GetTsumiki mocks base method.
func (m *MockTsumikiRepository) GetTsumiki(watchUserID *int, tsumikiID int) (*schema.Tsumiki, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTsumiki", watchUserID, tsumikiID)
	ret0, _ := ret[0].(*schema.Tsumiki)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTsumiki indicates an expected call of GetTsumiki.
func (mr *MockTsumikiRepositoryMockRecorder) GetTsumiki(watchUserID, tsumikiID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTsumiki", reflect.TypeOf((*MockTsumikiRepository)(nil).GetTsumiki), watchUserID, tsumikiID)
}

// GetTsumikiBlocks mocks base method.
func (m *MockTsumikiRepository) GetTsumikiBlocks(tsumikiID int, pageSize, page int) ([]schema.TsumikiBlockView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTsumikiBlocks", tsumikiID, pageSize, page)
	ret0, _ := ret[0].([]schema.TsumikiBlockView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTsumikiBlocks indicates an expected call of GetTsumikiBlocks.
func (mr *MockTsumikiRepositoryMockRecorder) GetTsumikiBlocks(tsumikiID, pageSize, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTsumikiBlocks", reflect.TypeOf((*MockTsumikiRepository)(nil).GetTsumikiBlocks), tsumikiID, pageSize, page)
}

// GetTsumikis mocks base method.
func (m *MockTsumikiRepository) GetTsumikis(watchUserID *int, pageSize, page int, authorID *int, workID *int, keyword string) ([]schema.Tsumiki, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTsumikis", watchUserID, pageSize, page, authorID, workID, keyword)
	ret0, _ := ret[0].([]schema.Tsumiki)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTsumikis indicates an expected call of GetTsumikis.
func (mr *MockTsumikiRepositoryMockRecorder) GetTsumikis(watchUserID, pageSize, page, authorID, workID, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTsumikis", reflect.TypeOf((*MockTsumikiRepository)(nil).GetTsumikis), watchUserID, pageSize, page, authorID, workID, keyword)
}

// UpdateTsumiki mocks base method.
func (m *MockTsumikiRepository) UpdateTsumiki(tsumikiID int, title string, visibility string, workID *int) (*schema.Tsumiki, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTsumiki", tsumikiID, title, visibility, workID)
	ret0, _ := ret[0].(*schema.Tsumiki)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTsumiki indicates an expected call of UpdateTsumiki.
func (mr *MockTsumikiRepositoryMockRecorder) UpdateTsumiki(tsumikiID, title, visibility, workID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTsumiki", reflect.TypeOf((*MockTsumikiRepository)(nil).UpdateTsumiki), tsumikiID, title, visibility, workID)
}

// UpdateTsumikiThumbnail mocks base method.
func (m *MockTsumikiRepository) UpdateTsumikiThumbnail(tsumikiID int, thumbnailID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTsumikiThumbnail", tsumikiID, thumbnailID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTsumikiThumbnail indicates an expected call of UpdateTsumikiThumbnail.
func (mr *MockTsumikiRepositoryMockRecorder) UpdateTsumikiThumbnail(tsumikiID, thumbnailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTsumikiThumbnail", reflect.TypeOf((*MockTsumikiRepository)(nil).UpdateTsumikiThumbnail), tsumikiID, thumbnailID)
}
