// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mock/mock_user.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	schema "tsumiki/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUserByDiscord mocks base method.
func (m *MockUserRepository) CreateUserByDiscord(name, avatar_url, discord_user_id, guild_id string) (*schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserByDiscord", name, avatar_url, discord_user_id, guild_id)
	ret0, _ := ret[0].(*schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserByDiscord indicates an expected call of CreateUserByDiscord.
func (mr *MockUserRepositoryMockRecorder) CreateUserByDiscord(name, avatar_url, discord_user_id, guild_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserByDiscord", reflect.TypeOf((*MockUserRepository)(nil).CreateUserByDiscord), name, avatar_url, discord_user_id, guild_id)
}

// FindByDiscordUserId mocks base method.
func (m *MockUserRepository) FindByDiscordUserId(id string) (*schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDiscordUserId", id)
	ret0, _ := ret[0].(*schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDiscordUserId indicates an expected call of FindByDiscordUserId.
func (mr *MockUserRepositoryMockRecorder) FindByDiscordUserId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDiscordUserId", reflect.TypeOf((*MockUserRepository)(nil).FindByDiscordUserId), id)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(id int) (*schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), id)
}

// UpdateAvatarUrl mocks base method.
func (m *MockUserRepository) UpdateAvatarUrl(userID int, avatarUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarUrl", userID, avatarUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatarUrl indicates an expected call of UpdateAvatarUrl.
func (mr *MockUserRepositoryMockRecorder) UpdateAvatarUrl(userID, avatarUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarUrl", reflect.TypeOf((*MockUserRepository)(nil).UpdateAvatarUrl), userID, avatarUrl)
}
