// Code generated by MockGen. DO NOT EDIT.
// Source: tsumiki-block.go
//
// Generated by this command:
//
//	mockgen -source=tsumiki-block.go -destination=mock/mock_tsumiki_block.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	schema "tsumiki/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockTsumikiBlockRepository is a mock of TsumikiBlockRepository interface.
type MockTsumikiBlockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTsumikiBlockRepositoryMockRecorder
	isgomock struct{}
}

// MockTsumikiBlockRepositoryMockRecorder is the mock recorder for MockTsumikiBlockRepository.
type MockTsumikiBlockRepositoryMockRecorder struct {
	mock *MockTsumikiBlockRepository
}

// NewMockTsumikiBlockRepository creates a new mock instance.
func NewMockTsumikiBlockRepository(ctrl *gomock.Controller) *MockTsumikiBlockRepository {
	mock := &MockTsumikiBlockRepository{ctrl: ctrl}
	mock.recorder = &MockTsumikiBlockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTsumikiBlockRepository) EXPECT() *MockTsumikiBlockRepositoryMockRecorder {
	return m.recorder
}

// CreateBlock mocks base method.
func (m *MockTsumikiBlockRepository) CreateBlock(tsumikiID int, message *string, percentage int, condition int) (*schema.TsumikiBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", tsumikiID, message, percentage, condition)
	ret0, _ := ret[0].(*schema.TsumikiBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockTsumikiBlockRepositoryMockRecorder) CreateBlock(tsumikiID, message, percentage, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockTsumikiBlockRepository)(nil).CreateBlock), tsumikiID, message, percentage, condition)
}

// GetLatestBlockID mocks base method.
func (m *MockTsumikiBlockRepository) GetLatestBlockID(tsumikiID int) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlockID", tsumikiID)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlockID indicates an expected call of GetLatestBlockID.
func (mr *MockTsumikiBlockRepositoryMockRecorder) GetLatestBlockID(tsumikiID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlockID", reflect.TypeOf((*MockTsumikiBlockRepository)(nil).GetLatestBlockID), tsumikiID)
}

// IsBelongToTsumiki mocks base method.
func (m *MockTsumikiBlockRepository) IsBelongToTsumiki(tsumikiID int, blockID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBelongToTsumiki", tsumikiID, blockID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBelongToTsumiki indicates an expected call of IsBelongToTsumiki.
func (mr *MockTsumikiBlockRepositoryMockRecorder) IsBelongToTsumiki(tsumikiID, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBelongToTsumiki", reflect.TypeOf((*MockTsumikiBlockRepository)(nil).IsBelongToTsumiki), tsumikiID, blockID)
}

// SoftDeleteBlock mocks base method.
func (m *MockTsumikiBlockRepository) SoftDeleteBlock(blockID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteBlock", blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteBlock indicates an expected call of SoftDeleteBlock.
func (mr *MockTsumikiBlockRepositoryMockRecorder) SoftDeleteBlock(blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteBlock", reflect.TypeOf((*MockTsumikiBlockRepository)(nil).SoftDeleteBlock), blockID)
}

// UpdateBlock mocks base method.
func (m *MockTsumikiBlockRepository) UpdateBlock(blockID int, message *string, percentage int, condition int) (*schema.TsumikiBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlock", blockID, message, percentage, condition)
	ret0, _ := ret[0].(*schema.TsumikiBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockTsumikiBlockRepositoryMockRecorder) UpdateBlock(blockID, message, percentage, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockTsumikiBlockRepository)(nil).UpdateBlock), blockID, message, percentage, condition)
}
