// Code generated by MockGen. DO NOT EDIT.
// Source: thumbnail.go
//
// Generated by this command:
//
//	mockgen -source=thumbnail.go -destination=mock/mock_thumbnail.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	schema "tsumiki/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockThumbnailRepository is a mock of ThumbnailRepository interface.
type MockThumbnailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThumbnailRepositoryMockRecorder
	isgomock struct{}
}

// MockThumbnailRepositoryMockRecorder is the mock recorder for MockThumbnailRepository.
type MockThumbnailRepositoryMockRecorder struct {
	mock *MockThumbnailRepository
}

// NewMockThumbnailRepository creates a new mock instance.
func NewMockThumbnailRepository(ctrl *gomock.Controller) *MockThumbnailRepository {
	mock := &MockThumbnailRepository{ctrl: ctrl}
	mock.recorder = &MockThumbnailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThumbnailRepository) EXPECT() *MockThumbnailRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockThumbnailRepository) Create(userID int, path string) (*schema.ThumbnailUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, path)
	ret0, _ := ret[0].(*schema.ThumbnailUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockThumbnailRepositoryMockRecorder) Create(userID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockThumbnailRepository)(nil).Create), userID, path)
}

// Get mocks base method.
func (m *MockThumbnailRepository) Get(thumbnailID int) (*schema.ThumbnailUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", thumbnailID)
	ret0, _ := ret[0].(*schema.ThumbnailUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockThumbnailRepositoryMockRecorder) Get(thumbnailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockThumbnailRepository)(nil).Get), thumbnailID)
}

// IsInUse mocks base method.
func (m *MockThumbnailRepository) IsInUse(thumbnailID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInUse", thumbnailID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsInUse indicates an expected call of IsInUse.
func (mr *MockThumbnailRepositoryMockRecorder) IsInUse(thumbnailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInUse", reflect.TypeOf((*MockThumbnailRepository)(nil).IsInUse), thumbnailID)
}
