// Code generated by MockGen. DO NOT EDIT.
// Source: tsumiki-block-media.go
//
// Generated by this command:
//
//	mockgen -source=tsumiki-block-media.go -destination=mock/mock_tsumiki_block_media.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	schema "tsumiki/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockTsumikiBlockMediaRepository is a mock of TsumikiBlockMediaRepository interface.
type MockTsumikiBlockMediaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTsumikiBlockMediaRepositoryMockRecorder
	isgomock struct{}
}

// MockTsumikiBlockMediaRepositoryMockRecorder is the mock recorder for MockTsumikiBlockMediaRepository.
type MockTsumikiBlockMediaRepositoryMockRecorder struct {
	mock *MockTsumikiBlockMediaRepository
}

// NewMockTsumikiBlockMediaRepository creates a new mock instance.
func NewMockTsumikiBlockMediaRepository(ctrl *gomock.Controller) *MockTsumikiBlockMediaRepository {
	mock := &MockTsumikiBlockMediaRepository{ctrl: ctrl}
	mock.recorder = &MockTsumikiBlockMediaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTsumikiBlockMediaRepository) EXPECT() *MockTsumikiBlockMediaRepositoryMockRecorder {
	return m.recorder
}

// CreateMedia mocks base method.
func (m *MockTsumikiBlockMediaRepository) CreateMedia(url string, mediaType string) (*schema.TsumikiBlockMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedia", url, mediaType)
	ret0, _ := ret[0].(*schema.TsumikiBlockMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMedia indicates an expected call of CreateMedia.
func (mr *MockTsumikiBlockMediaRepositoryMockRecorder) CreateMedia(url, mediaType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedia", reflect.TypeOf((*MockTsumikiBlockMediaRepository)(nil).CreateMedia), url, mediaType)
}

// SetMediaRelation mocks base method.
func (m *MockTsumikiBlockMediaRepository) SetMediaRelation(blockID int, updatedMediaIDs []int) ([]schema.TsumikiBlockMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMediaRelation", blockID, updatedMediaIDs)
	ret0, _ := ret[0].([]schema.TsumikiBlockMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMediaRelation indicates an expected call of SetMediaRelation.
func (mr *MockTsumikiBlockMediaRepositoryMockRecorder) SetMediaRelation(blockID, updatedMediaIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMediaRelation", reflect.TypeOf((*MockTsumikiBlockMediaRepository)(nil).SetMediaRelation), blockID, updatedMediaIDs)
}
