// Code generated by MockGen. DO NOT EDIT.
// Source: tsumiki_favorite.go
//
// Generated by this command:
//
//	mockgen -source=tsumiki_favorite.go -destination=mock/mock_tsumiki_favorite.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	schema "tsumiki/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockTsumikiFavoriteRepository is a mock of TsumikiFavoriteRepository interface.
type MockTsumikiFavoriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTsumikiFavoriteRepositoryMockRecorder
	isgomock struct{}
}

// MockTsumikiFavoriteRepositoryMockRecorder is the mock recorder for MockTsumikiFavoriteRepository.
type MockTsumikiFavoriteRepositoryMockRecorder struct {
	mock *MockTsumikiFavoriteRepository
}

// NewMockTsumikiFavoriteRepository creates a new mock instance.
func NewMockTsumikiFavoriteRepository(ctrl *gomock.Controller) *MockTsumikiFavoriteRepository {
	mock := &MockTsumikiFavoriteRepository{ctrl: ctrl}
	mock.recorder = &MockTsumikiFavoriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTsumikiFavoriteRepository) EXPECT() *MockTsumikiFavoriteRepositoryMockRecorder {
	return m.recorder
}

// SetFavoriteCount mocks base method.
func (m *MockTsumikiFavoriteRepository) SetFavoriteCount(tsumikiID, userID, count int) (*schema.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFavoriteCount", tsumikiID, userID, count)
	ret0, _ := ret[0].(*schema.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFavoriteCount indicates an expected call of SetFavoriteCount.
func (mr *MockTsumikiFavoriteRepositoryMockRecorder) SetFavoriteCount(tsumikiID, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFavoriteCount", reflect.TypeOf((*MockTsumikiFavoriteRepository)(nil).SetFavoriteCount), tsumikiID, userID, count)
}
