// Code generated by MockGen. DO NOT EDIT.
// Source: media.go
//
// Generated by this command:
//
//	mockgen -source=media.go -destination=mock/mock_media.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMediaService is a mock of MediaService interface.
type MockMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceMockRecorder
	isgomock struct{}
}

// MockMediaServiceMockRecorder is the mock recorder for MockMediaService.
type MockMediaServiceMockRecorder struct {
	mock *MockMediaService
}

// NewMockMediaService creates a new mock instance.
func NewMockMediaService(ctrl *gomock.Controller) *MockMediaService {
	mock := &MockMediaService{ctrl: ctrl}
	mock.recorder = &MockMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaService) EXPECT() *MockMediaServiceMockRecorder {
	return m.recorder
}

// ResolveURL mocks base method.
func (m *MockMediaService) ResolveURL(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveURL", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// ResolveURL indicates an expected call of ResolveURL.
func (mr *MockMediaServiceMockRecorder) ResolveURL(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveURL", reflect.TypeOf((*MockMediaService)(nil).ResolveURL), path)
}

// UploadAvatar mocks base method.
func (m *MockMediaService) UploadAvatar(ctx context.Context, userID int, r io.Reader, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, r, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockMediaServiceMockRecorder) UploadAvatar(ctx, userID, r, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockMediaService)(nil).UploadAvatar), ctx, userID, r, contentType)
}

// UploadThumbnail mocks base method.
func (m *MockMediaService) UploadThumbnail(ctx context.Context, userID int, r io.Reader, contentType, ext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadThumbnail", ctx, userID, r, contentType, ext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadThumbnail indicates an expected call of UploadThumbnail.
func (mr *MockMediaServiceMockRecorder) UploadThumbnail(ctx, userID, r, contentType, ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadThumbnail", reflect.TypeOf((*MockMediaService)(nil).UploadThumbnail), ctx, userID, r, contentType, ext)
}

// UploadTsumikiMedia mocks base method.
func (m *MockMediaService) UploadTsumikiMedia(ctx context.Context, tsumikiID int, r io.Reader, contentType, ext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTsumikiMedia", ctx, tsumikiID, r, contentType, ext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadTsumikiMedia indicates an expected call of UploadTsumikiMedia.
func (mr *MockMediaServiceMockRecorder) UploadTsumikiMedia(ctx, tsumikiID, r, contentType, ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTsumikiMedia", reflect.TypeOf((*MockMediaService)(nil).UploadTsumikiMedia), ctx, tsumikiID, r, contentType, ext)
}
