Enum visibility {
    public
    limited
}

Enum media_type {
    image
    audio
    video
}

Table users {
    id int [pk, increment]
    discord_user_id int [not null, unique]
    name varchar [not null]
    guild_id int [not null]
    thumbnail_url varchar [not null]
    created_at timestamp  [default: `now()`]
    updated_at timestamp
}

Table tsumikis {
    id int [pk, increment]
    title varchar [not null]
    thumbnail_url varchar [not null]
    visibility visibility [not null]
    miruko_watching_duration int  // 単位は秒
    work_id int [ref: > works.id, not null]
    user_id int [ref: > users.id, not null]
    created_at timestamp  [default: `now()`]
    updated_at timestamp
}

Table tsumiki_blocks {
    id int [pk, increment]
    message varchar  // メッセージかメディアはいずれか必須(ロジックで担保する？)
    percentage int [not null]
    condition int [not null]  // 1-5
    next_block_id int [unique, ref: - tsumiki_blocks.id]
    tsumiki_id int [ref: > tsumikis.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp
    deleted_at timestamp  // ソフトデリートとして、データは隠しつつ連結の穴抜けを解消する

    Indexes {
        (tsumiki_id, next_block_id) [name: "idx_tsumiki_blocks_tsumiki_id_next_block_id"]
    }
}

Table tsumiki_block_medias {
    id int [pk, increment]
    type media_type [not null]
    url varchar [not null]
    tsumiki_block_id int [ref: > tsumiki_blocks.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp
}

Table works {
    id int [pk, increment]
    title varchar [not null]
    description varchar
    thumbnail_url varchar
    owner_user_id int [ref: > users.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp
}

Table tsumiki_favorites {
    tsumiki_id int [pk, ref: > tsumikis.id]
    user_id int [pk, ref: > users.id, not null]
    counts int [not null]  // maxは10? 50? 100? ロジックで担保する？
    created_at timestamp [default: `now()`]
    updated_at timestamp
}

Table tsumiki_comments {
    id int [pk, increment]
    tsumiki_id int [ref: > tsumikis.id, not null]
    user_id int [ref: > users.id, not null]
    message varchar [not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp
}

Table tsumiki_reactions {
    id int [pk, increment]
    tsumiki_id int [ref: > tsumikis.id, not null]
    user_id int [ref: > users.id, not null]
    reaction_id int [ref: > reactions.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp

    Indexes {
        (tsumiki_id, user_id, reaction_id) [unique]
    }
}

Table tsumiki_block_comments {
    id int [pk, increment]
    tsumiki_block_id int [ref: > tsumiki_blocks.id, not null]
    user_id int [ref: > users.id, not null]
    message varchar [not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp
}

Table tsumiki_block_reactions {
    id int [pk, increment]
    tsumiki_block_id int [ref: > tsumiki_blocks.id, not null]
    user_id int [ref: > users.id, not null]
    reaction_id int [ref: > reactions.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp

    Indexes {
        (tsumiki_block_id, user_id, reaction_id) [unique]
    }
}

Table reactions {
    id int [pk, increment]
    shortcode varchar [unique, not null]
    icon_url varchar [not null]
    is_active boolean [not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp
}
