Enum visibility {
    public
    limited
}

Enum media_type {
    image
    audio
    video
}

Table users {
    id int [pk, increment]
    discord_user_id varchar [unique]
    name varchar [not null]
    guild_id varchar
    avatar_url varchar
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
}

Table tsumikis {
    id int [pk, increment]
    title varchar [not null]
    thumbnail_url varchar [not null]
    visibility visibility [not null]
    miruko_watching_duration int [note: '単位は秒']
    work_id int [ref: > works.id]
    user_id int [ref: > users.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
}

Table tsumiki_blocks {
    id int [pk, increment]
    message varchar [note: 'メッセージかメディアはいずれか必須(ロジックで担保)']
    percentage int [not null]
    condition int [not null, note: '1~5の値を取る(ロジックで担保)']
    next_block_id int [unique, ref: - tsumiki_blocks.id]
    tsumiki_id int [ref: > tsumikis.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
    deleted_at timestamp [note: 'ソフトデリートとして、データは隠しつつ連結の穴抜けを解消する']

    Indexes {
        (tsumiki_id, next_block_id) [name: "idx_tsumiki_blocks_tsumiki_id_next_block_id"]
    }
}

Table tsumiki_block_medias {
    id int [pk, increment]
    type media_type [not null]
    url varchar [not null]
    order int
    tsumiki_block_id int [ref: > tsumiki_blocks.id]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
    Indexes {
        (tsumiki_block_id, order) [unique]
    }
}

Table works {
    id int [pk, increment]
    title varchar [not null]
    description varchar
    thumbnail_url varchar
    owner_user_id int [ref: > users.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
}

Table tsumiki_favorites {
    tsumiki_id int [pk, ref: > tsumikis.id]
    user_id int [pk, ref: > users.id, not null]
    counts int [not null, note: 'maxは10(ロジックで担保)']
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
}

Table tsumiki_comments {
    id int [pk, increment]
    tsumiki_id int [ref: > tsumikis.id, not null]
    tsumiki_block_id int [ref: > tsumiki_blocks.id, note: 'ブロックに向けたコメントはこっち']
    user_id int [ref: > users.id, not null]
    message varchar [not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
}

Table tsumiki_reactions {
    id int [pk, increment]
    tsumiki_id int [ref: > tsumikis.id, not null]
    user_id int [ref: > users.id, not null]
    reaction_id int [ref: > reactions.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']

    Indexes {
        (tsumiki_id, user_id, reaction_id) [unique]
    }
}

Table tsumiki_block_reactions {
    id int [pk, increment]
    tsumiki_block_id int [ref: > tsumiki_blocks.id, not null]
    user_id int [ref: > users.id, not null]
    reaction_id int [ref: > reactions.id, not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']

    Indexes {
        (tsumiki_block_id, user_id, reaction_id) [unique]
    }
}

Table reactions {
    id int [pk, increment]
    shortcode varchar [unique, not null]
    icon_url varchar [not null]
    is_active boolean [not null]
    created_at timestamp [default: `now()`]
    updated_at timestamp [default: `now()`, note: 'ON UPDATE CURRENT_TIMESTAMP']
}
